[project]
name = "user"
version = "0.1.0"
dependencies = [
    "flask>=3.0,<4.0",
    "prometheus-flask-exporter>=0.23.2,<0.24",
    "psycopg2-binary>=2.9,<3.0",
    "gunicorn>=23.0,<24.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8,<9",
    "pytest-cov>=7,<8",
    "ruff>=0.6,<1.0",
    "bandit>=1.7,<2.0",
    "pip-audit>=2.7,<3.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
