apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: user-skaffold
build:
  artifacts:
    - image: user-skaffold
      context: .
  tagPolicy:
    gitCommit: {}
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      helm:
        releases:
          - name: user
            chartPath: helm
            namespace: psp
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
  - name: prod
    deploy:
      helm:
        releases:
          - name: user
            chartPath: helm
            namespace: psp
            setValueTemplates:
              image: "{{.IMAGE_FULLY_QUALIFIED}}"
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true
