#!/usr/bin/env bash
set -eou pipefail

VERSION=$1
CHART_DIR="helm/"
REGISTRY="ghcr.io/portfolio-solver-platform"
CHART_NAME="user"
CHART_REGISTRY="oci://$REGISTRY/charts"

echo "Packaging and publishing Helm Chart $VERSION..."

helm package "$CHART_DIR" --version "$VERSION"
helm push "$CHART_NAME-$VERSION.tgz" "$CHART_REGISTRY"

echo "Publish complete."
