name: CI
on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read

    uses: Portfolio-Solver-Platform/infrastructure/.github/workflows/python-ci.yaml@main
    with:
      code_audit_targets: "./src/"
