name: CI
on:
  pull_request:
  workflow_call:
permissions:
  contents: read
jobs:
  validate:
    name: Validate configuration
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install environment
        run: nix develop .#ci

      - name: Run checks
        run: nix develop .#ci --command pre-commit run -a

  ci:
    needs: validate
    permissions:
      contents: read
    uses: Portfolio-Solver-Platform/infrastructure/.github/workflows/python-ci.yaml@main
    with:
      code_audit_targets: "./src/"
