name: Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  push:
    needs: ci

    permissions:
      contents: read
      packages: write

    uses: Portfolio-Solver-Platform/infrastructure/.github/workflows/push.yaml@main
    with:
      image_name: 'user'
    secrets:
      repo_bot_private_key: ${{ secrets.REPO_BOT_PRIVATE_KEY }}
