name: Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  push:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io/portfolio-solver-platform
      IMAGE_NAME: user
      FILE_NAME: user-service.yaml
      MAIN_BRANCH_NAME: main

    steps:
      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF_NAME//\//-}
            sha=${GITHUB_SHA::8}
            ts=$(date +'%Y%m%d%H%M%S')
            echo "BUILD_TAG=${branch}-${sha}-${ts}" >> $GITHUB_ENV

      - name: Generate Tags
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}"
          TAGS="$IMAGE"

          if [ "$GITHUB_REF_NAME" == "${{ env.MAIN_BRANCH_NAME }}" ]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            echo "Building from main branch. 'latest' tag will be applied."
          fi

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true


      - name: Generate app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.INFRASTRUCTURE_BOT_ID }}
          private-key: ${{ secrets.INFRASTRUCTURE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: infrastructure

      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: Portfolio-Solver-Platform/infrastructure
          token: ${{ steps.app-token.outputs.token }}
          path: infrastructure
          ref: wip-flux

      - name: Update image tag in manifests
        run: |
          cd infrastructure/apps/base/
          yq -i ".spec.values.image = \"$IMAGE\"" ${{ env.FILE_NAME }}

      - name: Commit and push changes
        run: |
          cd infrastructure
          git config user.name "infrastructure-bot[bot]"
          git config user.email "infrastructure-bot[bot]@users.noreply.github.com"

          git add .
          git diff-index --quiet HEAD || git commit -m "chore($IMAGE_NAME): update $IMAGE_NAME image to ${{ env.BUILD_TAG }}"
          git push
